openapi: 3.0.0
info:
  title: Todo API
  version: '1.0'
  description: Todoで利用するためのAPI
  contact:
    name: contact
servers:
  - url: 'http://localhost:3000'
paths:
  /task/{id}:
    get:
      tags:
        - Task
      summary: Get task by ID.
      description: Returns a single Task model
      parameters:
        - name: id
          in: path
          description: task id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single Task model
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1
                  content: "ドキュメント作成"
    delete:
      tags:
        - Task
      summary: Delete task
      responses:
        200:
          description: OK
      description: Delete task.
      parameters:
        - name: id
          in: path
          description: task id
          required: true
          schema:
            type: integer
  /task:
    post:
      tags:
        - Task
      summary: Create a new task
      description: Create a new task
      parameters: []
      requestBody:
        description: task to create
        content:
          application/json:
            example:
              content: "ドキュメント作成"
      responses:
        '201':
          description: CREATED
  /task/file:
    post:
      tags:
        - Task
      summary: Write count of task in txt
      description: Write count of task in txt
      parameters: []
      responses:
        '201':
          description: CREATED
